### ISSUE TITLE
Playlist doesn't load in FF when using direct link to party

### ISSUE THREAD

**Issue by cmar0ck** [Festify/app#201]
Hi,

when opening a party URL (https://festify.us/party/-L************p) in Firefox without entering the party code beforehand the playlist and party title can't be loaded / load infinitely (see screenshot for details).

![festify_ff_loading_problem](https://user-images.githubusercontent.com/22705116/42220221-a2c3d74e-7ece-11e8-9e0e-7e363ef7577e.jpg)

Tested in FF 60.0.2 (Ubuntu 18.04) and FF 61.0 (Win7), both 64bit.

Note: Refreshing / reloading the page seems to fix the issue temporarily but after clearing FF's cache the issue reappears.

Can u help, pls?

**Comment by NeoLegends** [comment]
Hey!

Could you open the console (Right Click > Inspect Element > Console Tab) and show us the output if there is any?

**Comment by NeoLegends** [comment]
Yeah I can reproduce this. Working on a fix now.

**Comment by NeoLegends** [comment]
Fixed. Thanks for the heads-up!

**Comment by cmar0ck** [comment]
Wow, that was fast, thanks a lot! :)

I assume I have to be patient a little longer for the changes to be deployed?
(When testing the problem still persists...)

**Comment by NeoLegends** [comment]
Yeah this is not live yet. :)

**Comment by cmar0ck** [comment]
I see :) Last question, I promise:
Is there a chance it will go live before the 13th of July?
That would be really awesome as I intended to use Festify for an event on that date.

**Comment by NeoLegends** [comment]
> Is there a chance it will go live before the 13th of July?

Very likely, but is this really a big problem to you? Seems like it would only occur once "in a lifetime", no?

**Comment by cmar0ck** [comment]
Well, there will be numerous international guests and if only 100 of them try to use Festify with Firefox resulting in the queue not loading properly the first time they try it, they might be confused, disappointed or might even complain (not all of them are tech savvy), so the overall impression will suffer and that's something I'd like to avoid. I'd also like to keep the voting process as easy and streamlined as possible, so I'd definitely prefer the direct URL over the intermediate step of entering the party code. On the other hand I need to get print material (timetables, handouts, etc) done asap on which I planned to include the Festify URL and some instructions. So I'm depending on your decision and when you're going to deploy the fix...

**Comment by NeoLegends** [comment]
Fix is released now ✅

**Comment by cmar0ck** [comment]
Amazing! Thanks a bunch!
Do you have a donation link so I can fund you a party pizza and a sixpack as a little token of appreciation?

**Comment by cmar0ck** [comment]
![awesome](https://user-images.githubusercontent.com/22705116/42266242-24e1112c-7f76-11e8-94e3-69cc99daf6c0.png)


Donation is on the way.
