### ISSUE TITLE
Festify play one song, then stop playing after the song has ended

### ISSUE THREAD

**Issue by pasathaioum5** [Festify/app#306]
The legendary #290 issue kinda returns again. but this time it will stop after the first song finished playing. (stay in pause state)

**Comment by dmbeechy** [comment]
I'm having the same issue!

Also if I skip track manually it now will skip 2 tracks ahead?
Based on the timing alone I'm guessing they're related?

**Comment by MrCodZilla** [comment]
Looks related to #284 but is closed ( contains a rather large thread ) 
The only recent change was done by an issue I logged in #305

**Comment by leolabs** [comment]
Oh, hmm. The change I pushed couldn't have caused that. It only touched on the search results. But maybe the deploy included some other changes that I wasn't aware of. I'll roll it back for now but will try to find the culprit in the next few days :) 

This means that for now, explicit songs aren't shown in search, but playback should work as expected again.

**Comment by sebpwhite** [comment]
Just discovered festify. Great little app! Unfortunately I'm still seeing both what @pasathaioum5 and @dmbeechy describe above which are kind of showstoppers.

**Comment by pasathaioum5** [comment]
@leolabs still the same, sir.

**Comment by grantbowering** [comment]
Yeah, this is still going on for me as well.  When I saw this thread, I thought maybe it still had the problematic changes cached, but I've cleared my cache and the functionality didn't return.  Now I'm just sitting with my laptop in front of me logged in as the party admin and manually pushing skip and play every time a song finishes. 😩

**Comment by leolabs** [comment]
Hey everyone,

I've implemented a fix for this bug. Please excuse the long wait. Could you try it again on your side and report back whether everything works as expected again now?

This fix should also make sure that Festify doesn't skip a track after a song ended, which happened sporadically.

**Comment by sebpwhite** [comment]
Working on my side now. Much appreciated!

**Comment by pasathaioum5** [comment]
Working on my side now too, thank you very much.
